spring:
  profiles:
    active:
    - dev

---

server:
  port: 8001  #注册中心占用8001端口，冒号后边必须由空格

spring:
  profiles: dev
  application:
    name: microservice-config-eureka

eureka:
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka8001:8001/eureka/
  instance:
    hostname: eureka8001

---

server:
  port: 8001  #注册中心占用8001端口，冒号后边必须由空格

spring:
  profiles: test
  application:
    name: microservice-config-eureka

eureka:
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka8001:8001/eureka/
  instance:
    hostname: eureka8001