spring:
  profiles:
    active:
    - dev

---

server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservice-config-client

eureka:
  instance:
    hostname: eureka8001
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8001:8001/eureka/

---

server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservice-config-client

eureka:
  instance:
    hostname: eureka8001
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8001:8001/eureka/